In [2]:
import sys
sys.path.append("..")
from src.features import *
from src.data.make_dataset import *
%load_ext autoreload
%autoreload 2

c:\Users\ziacovino\AppData\Local\anaconda3\envs\mapc-python-keys\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
  return ogr_read(
c:\Users\ziacovino\AppData\Local\anaconda3\envs\mapc-python-keys\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  return ogr_read(

In [2]:
mmc_munis = ["Arlington", "Braintree", "Cambridge", "Chelsea", 
             "Everett", "Lynn", "Malden", "Melrose",
             "Medford","Newton", "Revere", "Somerville", "Quincy", 
              "Watertown", "Winthrop"]

In [5]:
from datetime import datetime
from src.data.weights import *
from src.features.zoning_nonconformity_scripts import *

gdf_list_overlay = []

for muni in mmc_munis:
    print(muni + ' processing starting at ' + str(datetime.now()))

    zoning_merge_check = test_merge(muni, 'overlay', zoning_check = True)
    gdf_list_overlay.append(zoning_merge_check)

all_zoning_overlay = pd.concat(gdf_list_overlay)

Arlington processing starting at 2025-11-04 11:10:47.969913
Total Rows in Roofprints
12297
Total Unique Parcel IDs
11912
11912
11912
11912
Rows in final join table for Building Structures
11912
Unique Parcels in Building Structures
11912
Rows in final parcel layer
12585
Unique Parcels in Final Parcel Layer
12585
Rows in overlap calc parcel layer
12585
Unique Parcels in overlap calc Parcel Layer
12585
importing overlay
     oid_  zo_code  muni_id       muni zo_abbr  \
227   NaN    10HAP     10.0  Arlington     HAP
228   NaN     10HB     10.0  Arlington      HB
229   NaN    10HCS     10.0  Arlington     HCS
230   NaN    10HJG     10.0  Arlington     HJG
231   NaN  10HMGCH     10.0  Arlington   HMGCH

                                 zo_name  shape_leng  Shape_Length  \
227                  Avon Place District         NaN    473.390254
228                    Broadway District         NaN    494.726706
229              Central Street District         NaN    577.465543
230                  Jason/Gray District         NaN   1936.261638
231  Mount Gilboa/Crescent Hill District         NaN   2714.290410

        Shape_Area                                           geometry
227   10640.665675  MULTIPOLYGON (((228836.288 907028.068, 228855....
228    7614.522025  MULTIPOLYGON (((228982.62 907098.067, 229004.3...
229   12912.153883  MULTIPOLYGON (((228269.04 907554.497, 228276.2...
230   75039.471068  MULTIPOLYGON (((228211.039 907356.606, 228204....
231  149687.474475  MULTIPOLYGON (((225926.057 909063.99, 225931.5...
{'More than Eight Units'}
Parcel Rows
1248
Unique LOC_IDS
1248
Joined Parcel Length
232
Split Zoned Parcels Detected
Clean Join successful?
True
Any Parcels missing a Zone Code?
1031
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
2
Zoning Table post De-Dupe
2
Parcels with Zoning Table Joined
1248
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning

c:\Users\ziacovino\Desktop\rightsizing-zoning-analysis\notebooks\..\src\features\nested_functions.py:309: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  mapc_lpd = pd.read_csv(muni_lpd_path, dtype={

Total Rows in Roofprints
22872
Total Unique Parcel IDs
22436
22436
22436
22436
Rows in final join table for Building Structures
22436
Unique Parcels in Building Structures
22436
Rows in final parcel layer
23962
Unique Parcels in Final Parcel Layer
23962
Rows in overlap calc parcel layer
23962
Unique Parcels in overlap calc Parcel Layer
23962
importing overlay
   oid_ zo_code  muni_id    muni zo_abbr zo_name  shape_leng  Shape_Length  \
0   NaN  207MRT    207.0  Newton     MRT    None         NaN    153.803093
1   NaN  207VC2    207.0  Newton     VC2    None         NaN    121.859766
2   NaN  207VC2    207.0  Newton     VC2    None         NaN    355.679515
3   NaN  207VC2    207.0  Newton     VC2    None         NaN    246.272762
4   NaN  207VC2    207.0  Newton     VC2    None         NaN    346.017335

    Shape_Area                                           geometry
0  1330.446104  MULTIPOLYGON (((222394.626 899973.62, 222397.9...
1   943.843903  MULTIPOLYGON (((224025.146 896813.793, 224021....
2  5140.001189  MULTIPOLYGON (((224133.094 896888.606, 224150....
3  2923.065159  MULTIPOLYGON (((222314.176 897333.198, 222269....
4  7301.646114  MULTIPOLYGON (((222175.336 897369.332, 222159....
{'Three Family', 'More than Eight Units'}
Parcel Rows
1419
Unique LOC_IDS
1419
Joined Parcel Length
178
Split Zoned Parcels Detected
Clean Join successful?
True
Any Parcels missing a Zone Code?
1273
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
215
Zoning Table post De-Dupe
3
Parcels with Zoning Table Joined
1419
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning

c:\Users\ziacovino\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: organizePolygons() received an unexpected geometry.  Either a polygon with interior rings, or a polygon with less than 4 points, or a non-Polygon geometry.  Return arguments as a collection.
  return ogr_read(
c:\Users\ziacovino\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: Geometry of polygon of fid 12717 cannot be translated to Simple Geometry. All polygons will be contained in a multipolygon.
  return ogr_read(

Total Rows in Roofprints
10434
Total Unique Parcel IDs
10350
10350
10350
10350
Rows in final join table for Building Structures
10350
Unique Parcels in Building Structures
10350
Rows in final parcel layer
12660
Unique Parcels in Final Parcel Layer
12660
Rows in overlap calc parcel layer
12660
Unique Parcels in overlap calc Parcel Layer
12660
importing overlay
     oid_    zo_code  muni_id    muni zo_abbr  \
480   NaN  248OROD B    248.0  Revere  OROD B
481   NaN  248OROD A    248.0  Revere  OROD A
482   NaN  248OROD C    248.0  Revere  OROD C
483   NaN  248WTODOD    248.0  Revere  WTODOD
484   NaN    248SDOD    248.0  Revere    SDOD

                                               zo_name   shape_leng  \
480    Overlook Ridge Overlay District - Subdistrict B  5163.282360
481    Overlook Ridge Overlay District - Subdistrict A  2402.294727
482    Overlook Ridge Overlay District - Subdistrict C  1667.463117
483  Wonderland Transit-Oriented Development Overla...  6458.226729
484                     Suffolk Downs Overlay District  7601.536887

     Shape_Length     Shape_Area  \
480   1573.771610   47852.808247
481    732.220896   28219.089401
482    508.243777   15177.625004
483   1968.471440   81155.855599
484   2316.953077  220809.730100

                                              geometry
480  MULTIPOLYGON (((239300.423 910171.488, 239402....
481  MULTIPOLYGON (((239599.667 909619.383, 239594....
482  MULTIPOLYGON (((239615.89 909842.647, 239625.4...
483  MULTIPOLYGON (((241734.202 906918.034, 241734....
484  MULTIPOLYGON (((241762.875 905393, 241549.145 ...
{'More than Eight Units'}
Parcel Rows
1543
Unique LOC_IDS
1543
Joined Parcel Length
10
Parcels Sucessfully Overlayed
LOCIDs of Parcels without Zoning
set()
{'More than Eight Units'}
Somerville processing starting at 2025-11-04 11:12:57.540990
Total Rows in Roofprints
11946
Total Unique Parcel IDs
11681
11681
11681
11681
Rows in final join table for Building Structures
11681
Unique Parcels in Building Structures
11681
Rows in final parcel layer
12595
Unique Parcels in Final Parcel Layer
12593
Rows in overlap calc parcel layer
12595
Unique Parcels in overlap calc Parcel Layer
12593
importing overlay
     oid_ zo_code  muni_id        muni zo_abbr                     zo_name  \
504   NaN  274MPD    274.0  Somerville     MPD  Master Planned Development
505   NaN  274MPD    274.0  Somerville     MPD  Master Planned Development
506   NaN  274MPD    274.0  Somerville     MPD  Master Planned Development
507   NaN  274MPD    274.0  Somerville     MPD  Master Planned Development
508   NaN   274SB    274.0  Somerville      SB              Small Business

      shape_leng  Shape_Length    Shape_Area  \
504  4569.741075   1392.859865  84646.589382
505  1923.707659    586.347267  17437.249710
506  1290.108968    393.226000   5366.838993
507   736.589322    224.512874   1189.845623
508   653.289838    199.123141   1712.336258

                                              geometry
504  MULTIPOLYGON (((233774.022 902797.492, 233778....
505  MULTIPOLYGON (((235073.867 902536.776, 235067....
506  MULTIPOLYGON (((234810.669 902634.663, 234807....
507  MULTIPOLYGON (((234544.67 902720.915, 234544.7...
508  MULTIPOLYGON (((233367.34 902728.734, 233368.4...
{'No Residential Uses Allowed'}
Parcel Rows
4432
Unique LOC_IDS
4432
Joined Parcel Length
411
Split Zoned Parcels Detected
Clean Join successful?
True
Any Parcels missing a Zone Code?
4024
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
149
Zoning Table post De-Dupe
2
Parcels with Zoning Table Joined
4432
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning

In [7]:
all_zoning_overlay = all_zoning_overlay.dropna(subset = 'ZO_CODE')

In [3]:
from src.features.zoning_process_functions import *
findthena = mapc.get_landuse_data("Arlington")

findthena.geom_type.unique()

array(['Polygon', 'MultiPolygon'], dtype=object)

In [12]:
from src.features.zoning_nonconformity_scripts import*
arlington_test = run_zoning_nonconformity("Arlington", 'base', False)

<class 'geopandas.geodataframe.GeoDataFrame'>
Total Rows in Roofprints
12297
Total Unique Parcel IDs
11912
11912
11912
11912
Rows in final join table for Building Structures
11912
Unique Parcels in Building Structures
11912
Rows in final parcel layer
11920
Unique Parcels in Final Parcel Layer
1113
Rows in overlap calc parcel layer
11920
Unique Parcels in overlap calc Parcel Layer
1113
  ZO_CODE                               ZO_NAME  MUNI_ID       MUNI  \
0    10B1          Neighborhood Office District       10  Arlington
1    10B2        Neighborhood Business District       10  Arlington
2   10B2A               Major Business District       10  Arlington
3    10B3             Village Business District       10  Arlington
4    10B4  Vehicular Oriented Business District       10  Arlington

                     ZO_AldUse ZO_ABBR  ZO_USETY  \
0  No Residential Uses Allowed      B1       3.0
1  No Residential Uses Allowed      B2       3.0
2  No Residential Uses Allowed     B2A       3.0
3  No Residential Uses Allowed      B3       3.0
4  No Residential Uses Allowed      B4       3.0

                                            ZO_USEDE  MINLOTSIZE PCTLOTCOV  \
0  Single-family detached dwelling, two-family dw...         0.0       NaN
1  Single-family detached dwelling, two-family dw...         0.0       NaN
2  Provide retail and service to a large neighbor...         0.0       NaN
3  Retail, service and office uses catering to co...         0.0       NaN
4  Business oriented to motor vehicle traffic, in...         0.0       NaN

   LApDU  MAXFLRS  MAXHEIGHT  MAXDU  DUpAC  MAXFAR  MAX_GFA          EDITDATE
0    0.0      0.0        0.0    NaN    NaN     0.0      NaN  6/18/2025 3:24pm
1    0.0      0.0        0.0    NaN    NaN     0.0      NaN  6/18/2025 3:24pm
2    0.0      0.0        0.0    NaN    NaN     0.0      NaN  6/18/2025 3:24pm
3    0.0      0.0        0.0    NaN    NaN     0.0      NaN  6/18/2025 3:24pm
4    0.0      0.0        0.0    NaN    NaN     0.0      NaN  6/18/2025 3:24pm
Parcel Rows
11920
Unique LOC_IDS
1113
Joined Parcel Length
1650
Split Zoned Parcels Detected
Clean Join successful?
True
Any Parcels missing a Zone Code?
10808
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
281
Zoning Table post De-Dupe
19
Parcels with Zoning Table Joined
11920
Zones assigned to Parcels by Largest Share
Multifamily Parcels Detected in Overlay Zones

c:\Users\ziacovino\Desktop\rightsizing-zoning-analysis\notebooks\..\src\features\zoning_process_functions.py:94: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  idx = par_zon_join.fillna('999999').groupby('LOC_ID')['zone_share'].idxmax().reset_index()

{True, None}

KeyError: nan

In [ ]:
techynically_arlington = somerville_test.apply(lambda row:condo_conversion(luc = row[luc_adjusted],
                                                                                         units = row['EST_UNITS']),
                                                                                         axis = 1)

techynically_arlington

In [85]:
somerville_test

                        Test  Value
0      Original Parcel Count  12556
1        Parcel Layer Length  12556
2    LIDAR Join Parcel Count   4408
3          LIDAR Join Length   4408
4   Zoning Join Parcel Count   4408
5         Zoning Join Length   4408
6       Overlap Test Parcels   4408
7        Output Parcel Count   4408
8     Parcels without Zoning      0
9             Original Zones     17
10    Zones in Parcel Output     12
11                Total Rows   4408

In [23]:
#somerville_zoning = get_zoning_data('Somerville', 'base')
from src.features.nested_functions import *
somerville_parcels = get_landuse_data("Somerville")

In [ ]:
somerville_parcels

In [10]:
# file_name = get_file(dir_name=mapc_lpd_folder, 
#                          muni="Somerville"

muni = 'Arlington'

file_name = "LPDB_DRAFT_" + muni + "_Q2.2025.csv"

file_name

'LPDB_DRAFT_Arlington_Q2.2025.csv'

In [82]:
somerville_test = zoning_merge(somerville_zoning, somerville_parcels)

Parcel Rows
12556
Unique LOC_IDS
12556
Joined Parcel Length
14412
Split Zoned Parcels Detected
             LOC_ID  Unnamed: 0  TOWN_ID PROP_ID  BLDG_VAL  LAND_VAL  \
0  F_755832_2975949         155      274   3_C_1    292000   1167700
1  F_755906_2975924         181      274   3_C_2    462300    540100
2  F_755871_2975850         166      274  3_C_54    333100    573500
3  F_755832_2975949         155      274   3_C_1    292000   1167700
4  F_755906_2975924         181      274   3_C_2    462300    540100

   OTHER_VAL  TOTAL_VAL    FY  LOT_SIZE  ... MAXFLRS  MAXHEIGHT MAXDU DUpAC  \
0     164600    1624300  2023   19602.0  ...     0.0        0.0   0.0   NaN
1       3100    1005500  2023    3049.2  ...     0.0        0.0   0.0   NaN
2      13200     919800  2023    3484.8  ...     0.0        0.0   0.0   NaN
3     164600    1624300  2023   19602.0  ...     3.0        NaN   3.0   NaN
4       3100    1005500  2023    3049.2  ...     3.0        NaN   3.0   NaN

  MAXFAR MAX_GFA          EDITDATE  \
0    NaN     NaN  6/20/2025 3:10pm
1    NaN     NaN  6/20/2025 3:10pm
2    NaN     NaN  6/20/2025 3:10pm
3    NaN     NaN  8/12/2025 1:08pm
4    NaN     NaN  8/12/2025 1:08pm

                                            geometry    zone_area  \
0  POLYGON ((230388.198 907057.844, 230391.252 90...  1613.457818
1  POLYGON ((230388.198 907057.844, 230388.198 90...     0.000153
2  POLYGON ((230391.252 907055.348, 230375.977 90...     0.001006
3  MULTIPOLYGON (((230375.966 907036.438, 230375....     0.002456
4  POLYGON ((230397.641 907050.133, 230391.252 90...   292.917995

     zone_share
0  9.999959e-01
1  5.213038e-07
2  2.576506e-06
3  1.522189e-06
4  9.999985e-01

[5 rows x 92 columns]
             LOC_ID  zone_share
0  F_754983_2972507        9621
1  F_754985_2972668        9597
2  F_755002_2972459        9624
3  F_755024_2972633        9598
4  F_755066_2972566        7552
12553
Clean Join successful?
True
                 LOC_ID ZO_CODE
9621   F_754983_2972507  274CIV
9597   F_754985_2972668  274CIV
9624   F_755002_2972459   274UR
9598   F_755024_2972633  274CIV
7552   F_755066_2972566   274UR
...                 ...     ...
13038  F_770888_2967247   274CI
13436  F_771033_2962666   274CI
13435  F_771072_2962986   274CI
14403  F_771172_2961134   274HR
293    F_771267_2961296   274HR

[12553 rows x 2 columns]
Any Parcels missing a Zone Code?
3
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
1416
Zoning Table post De-Dupe
17
Parcels with Zoning Table Joined
12556
Parcels with Zoning De Duped
12556
Zones assigned to Parcels by Largest Share

In [81]:
zoning_table = pd.DataFrame(somerville_zoning.drop(columns= ['geometry', 'shape_leng','Shape_Length', 'Shape_Area', 'EDITDATE']))
zoning_table.drop_duplicates(ignore_index= True)
# print("Zoning Table pre-dedupe")
# print(len(zoning_table))
# zoning_table = zoning_table.drop_duplicates()
# print("Zoning Table post De-Dupe")
# print(len(zoning_table))

,oid_,zo_code,muni_id,muni,zo_abbr,zo_name,ZO_CODE,ZO_NAME,MUNI_ID,MUNI,...,ZO_USEDE,MINLOTSIZE,PCTLOTCOV,LApDU,MAXFLRS,MAXHEIGHT,MAXDU,DUpAC,MAXFAR,MAX_GFA
0,NaN,274ASMD,274.0,Somerville,ASMD,None,274ASMD,Assembly Square Mixed Use District,274,Somerville,...,"a variety of mid- and high-rise, transit orien...",5000.0,NaN,300.0,NaN,250.0,NaN,NaN,10.0,NaN
1,NaN,274CB,274.0,Somerville,CB,None,274CB,Commercial Business,274,Somerville,...,"entirely commercial, with concentrations of co...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,274CC3,274.0,Somerville,CC3,None,274CC3,NaN,274,Somerville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,274CC4,274.0,Somerville,CC4,None,274CC4,NaN,274,Somerville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,274CC5,274.0,Somerville,CC5,None,274CC5,NaN,274,Somerville,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,274CI,274.0,Somerville,CI,None,274CI,Commercial Industrial,274,Somerville,...,"entirely commercial, with uses that are typica...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,274CIV,274.0,Somerville,CIV,None,274CIV,Civic,274,Somerville,...,special district: characterized by public spac...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,274FAB,274.0,Somerville,FAB,None,274FAB,Fabrication,274,Somerville,...,The district is entirely commercial with build...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,274HR,274.0,Somerville,HR,None,274HR,High Rise,274,Somerville,...,"multi-unit, mixed-use, and commercial",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,274MR3,274.0,Somerville,MR3,None,274MR3,Mid-Rise 3 story,274,Somerville,...,up to three (3) stories in height,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
10,NaN,274MR4,274.0,Somerville,MR4,None,274MR4,Mid-Rise 4 story,274,Somerville,...,up to four (4) stories in height,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
11,NaN,274MR5,274.0,Somerville,MR5,None,274MR5,Mid-Rise 5 story,274,Somerville,...,up to five (5) stories in height,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
12,NaN,274MR6,274.0,Somerville,MR6,None,274MR6,Mid-Rise 6 story,274,Somerville,...,up to six (6) stories in height,NaN,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
13,NaN,274NR,274.0,Somerville,NR,None,274NR,Neighborhood Residential,274,Somerville,...,"one-, two-, and three-unit principal buildings",NaN,60.0,38.0,3.0,NaN,3.0,NaN,NaN,NaN
14,NaN,274PS,274.0,Somerville,PS,None,274PS,Powderhouse School,274,Somerville,...,special district: characterized by the adaptat...,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN
15,NaN,274TU,274.0,Somerville,TU,None,274TU,Tufts University,274,Somerville,...,special district: a large private research uni...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,274UR,274.0,Somerville,UR,None,274UR,Urban Residential,274,Somerville,...,multi-unit buildings where outdoor amenity spa...,NaN,65.0,1125.0,4.0,82.0,1500.0,NaN,NaN,NaN

In [ ]:

# join the rest of the zoning table back to the parcels
par_zon_join_fixed = pd.merge(somerville_test, zoning_table, left_on= 'ZO_CODE', right_on= 'ZO_CODE', how = "left")

In [12]:
print(len(['ls_conf', 'lc_conf', 'ld_conf', 'lu_conf', 'fl_conf', 'ht_conf', 'gfa_conf', 'du_conf', 'dua_conf', 'far_conf']))
print(len([14,15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]))
print(len(['LOT_SIZE', 'par_lot_cov', 'LOT_SIZE_GIS', luc_adjusted, 'MEDIAN_stories', 'MEDIAN', 'BLD_AREA', units, 'DUA', 'FAR']))

10
14
10

In [8]:
from src.features.zoning_nonconformity_scripts import *
hm = test_merge("Newton", "base")

1410
{'More than Eight Units', 'Single Family', 'Two Family', 'No Residential Uses Allowed'}
Split Zoned Parcels Detected
Clean Join successful?
True
Any Parcels missing a Zone Code?
0
Same number of parcels we started with?
True
Parcels with Zoning Table Joined
1410
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'More than Eight Units', 'Single Family', 'Two Family', 'No Residential Uses Allowed'}

ValueError: All arrays must be of the same length

In [2]:
town_name = "Newton"
rz_gdb = r"\\Data-Sync\Public\DataServices\Projects\Current_Projects\Housing\Zoning-to-Built-Form\Rightsizing Zoning\Rightsizing Zoning.gdb"
base_zone_summary = gpd.read_file(rz_gdb, layer= "mmc_base_zone_scores")
base_zone_summary_muni = base_zone_summary[base_zone_summary['CITY'] == town_name]

In [ ]:

all_munis_by_zone_table = pd.DataFrame(base_zone_summary.drop(columns = 'geometry'))
 
all_munis_by_zone_table.to_csv(r"C:\Users\ziacovino\OneDrive - Metropolitan Area Planning Council\Metro Mayors Housing Task Force\Phase 2 Scope of Work\Rightsizing Zoning Project\Data\Analysis Outputs\mmc_base_zone_scores.csv")

In [4]:
parcel_outputs = gpd.read_file(rz_gdb, layer= "Newton_conformityscores_base")

parce_outputs_csv = pd.DataFrame(parcel_outputs.drop(columns = 'geometry'))
 
parce_outputs_csv.to_csv(r"C:\Users\ziacovino\OneDrive - Metropolitan Area Planning Council\Metro Mayors Housing Task Force\Phase 2 Scope of Work\Rightsizing Zoning Project\Data\Analysis Outputs\mmc_base_parcel_scores.csv")

In [4]:
parcel_outputs_zone = parcel_outputs[['ZO_CODE', 'CITY','size_sum', 'shape_sum', 'dense_sum',
                              'size_count', 'shape_count', 'dense_count',
                              'Total', 'Measures', 'geometry']].dissolve(by = ['ZO_CODE', 'CITY'],
                                       aggfunc = 'mean')

In [5]:
from src.data.make_dataset import zoning_overlay_layer

set(zoning_overlay_layer['zo_code'])

{'10HAP',
 '10HB',
 '10HCS',
 '10HJG',
 '10HMGCH',
 '10HPS',
 '10HR',
 '10MBMF',
 '10NMF',
 '165MCMOD MC',
 '165MCMOD MC HIGH RISE',
 '165MCMOD MD1',
 '165MCMOD MD2',
 '165MCMOD OG',
 '165MEOD',
 '165MMU - 1',
 '178RCOD',
 '178SGD',
 '207MRT',
 '207VC2',
 '207VC3',
 '243MCMOD',
 '243TOD',
 '248GSSGOD',
 '248HD Zone',
 '248LD Zone',
 '248LL Zone',
 '248North Revere Zone',
 '248OROD A',
 '248OROD B',
 '248OROD C',
 '248RROD',
 '248SASGOD A',
 '248SASGOD B',
 '248SDOD',
 '248WTODOD',
 '274MPD',
 '274SB',
 '314ALOD',
 '314AODD',
 '314R/SOD',
 '314RD',
 '314TODO',
 '40Billboard District',
 '40MBTA 1 Redline NORTH',
 '40MBTA 2 Redline SOUTH',
 '40MBTA 3 Redline Village',
 '40MBTA 4 Greenbush BWLD',
 '40PUD',
 '40Village Overlay',
 '46Dean Rd',
 '46F-1.0',
 '46G-(DP)',
 '46G-1.0',
 '46G-1.75(CC)',
 '46G-1.75(LSH)',
 '46G-1.75(WS)',
 '46G-2.0',
 '46G-2.0(CA)',
 '46GMR-2.0',
 '46H-MS',
 '46H-MS-O',
 '46H-MSN',
 '46H-MST',
 '46I-(EISD)',
 '46I-1.0',
 '46L-0.5',
 '46L-0.5(CL)',
 '46L-1.0',
 '46M-0.5',
 '46M-1.0',
 '46M-1.0(CAM)',
 '46M-1.5',
 '46M-2.0',
 '46M-2.5',
 '46Middle Beacon',
 '46North',
 '46Northeast',
 '46O-1.0',
 '46O-2.0(CH)',
 '46S-0.5P',
 '46S-0.75P',
 '46S-10',
 '46S-15',
 '46S-25',
 '46S-40',
 '46S-7',
 '46SC-10',
 '46SC-7',
 '46Southeast',
 '46T-5',
 '46T-6',
 '49GJPOD',
 '49HS',
 '49MMRMI',
 '57AROD',
 '57FOD',
 '57GASGOD',
 '57GASGOD\n',
 '57WCOD',
 '93RCOD',
 '93ROD'}

In [14]:
from src.features.nested_functions import*
res_zoning = get_zoning_data("Newton")

In [4]:
mmc_munis = ["Arlington", "Braintree", "Brookline", "Cambridge", "Chelsea", 
             "Everett", "Lynn", "Malden", "Melrose",
             "Medford","Newton", "Quincy", "Revere", 
             "Somerville", "Watertown", "Winthrop"]


from src.features.zoning_nonconformity_scripts import *
muni_test_merge = []
for muni in mmc_munis:
    test = test_merge(muni, "base")
    muni_test_merge.append(test)

muni_test_merge_full = pd.concat(muni_test_merge)

12585
12297
Total Rows in Roofprints
12297
Total Unique Parcel IDs
11912
11912
11912
11912
Rows in final join table for Building Structures
11912
Unique Parcels in Building Structures
11912
Rows in final parcel layer
12585
Unique Parcels in Final Parcel Layer
12585
Rows in overlap calc parcel layer
12585
Unique Parcels in overlap calc Parcel Layer
12585
12585
1248
1248
{'Single Family', 'No Residential Uses Allowed', 'Two Family'}
Parcel Rows
1248
Unique LOC_IDS
1248
Joined Parcel Length
1457
Split Zoned Parcels Detected
1248
Clean Join successful?
True
                LOC_ID ZO_CODE
1456  F_738670_2978925    10R2
1455  F_738773_2978963    10R2
1453  F_738806_2979451    10R2
1451  F_739134_2979442    10R2
1454  F_739179_2979387    10R2
...                ...     ...
821   F_754975_2976269    10R2
815   F_754985_2976031    10R2
791   F_754994_2975131    10R5
820   F_755013_2976255    10R2
794   F_755142_2975831    10R5

[1248 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
281
Zoning Table post De-Dupe
19
Parcels with Zoning Table Joined
1248
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'No Residential Uses Allowed', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories             27
5          ht_conf       MAXHEIGHT              MEDIAN             27
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0    Arlington
1    Arlington
2    Arlington
3    Arlington
4    Arlington
5    Arlington
6    Arlington
7    Arlington
8    Arlington
9    Arlington
11650
10541
Total Rows in Roofprints
10541
Total Unique Parcel IDs
10345
10345
10345
10345
Rows in final join table for Building Structures
10345
Unique Parcels in Building Structures
10345
Rows in final parcel layer
11650
Unique Parcels in Final Parcel Layer
11650
Rows in overlap calc parcel layer
11650
Unique Parcels in overlap calc Parcel Layer
11650
11650
213
213
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Parcel Rows
213
Unique LOC_IDS
213
Joined Parcel Length
348
Split Zoned Parcels Detected
213
Clean Join successful?
True
               LOC_ID ZO_CODE
174  F_781453_2901628  40COMM
98   F_783247_2896694  40ResA
171  F_783945_2898115  40ResA
1    F_784037_2897419  40ResA
3    F_784307_2897470   40GBD
..                ...     ...
217  F_799867_2904808  40ResB
71   F_799965_2908033  40ResB
186  F_799970_2905421  40BWLD
145  F_800971_2908952  40ResB
236  F_801082_2909278  40ResB

[213 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
879
Zoning Table post De-Dupe
10
Parcels with Zoning Table Joined
213
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories              6
5          ht_conf       MAXHEIGHT              MEDIAN              6
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0    Braintree
1    Braintree
2    Braintree
3    Braintree
4    Braintree
5    Braintree
6    Braintree
7    Braintree
8    Braintree
9    Braintree
8451
7337
Total Rows in Roofprints
7337
Total Unique Parcel IDs
7082
7082
7082
7082
Rows in final join table for Building Structures
7082
Unique Parcels in Building Structures
7082
Rows in final parcel layer
8452
Unique Parcels in Final Parcel Layer
8452
Rows in overlap calc parcel layer
8452
Unique Parcels in overlap calc Parcel Layer
8452
8452
2044
2044
{'Single Family', 'Three Family', 'Four to Eight Units', 'Two Family'}
Parcel Rows
2044
Unique LOC_IDS
2044
Joined Parcel Length
2608
Split Zoned Parcels Detected
2044
Clean Join successful?
True
                LOC_ID  ZO_CODE
517   F_744407_2941064    46S-7
2035  F_744734_2941266    46T-5
1537  F_744912_2941510  46M-1.0
1529  F_744979_2941314  46M-1.0
1538  F_745119_2941617  46M-1.0
...                ...      ...
11    F_762353_2951913  46M-2.0
23    F_762386_2952144  46M-2.0
1939  F_762447_2950707    46T-5
1794  F_762466_2950663    46T-5
214   F_762504_2951009  46M-2.0

[2044 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
32
Zoning Table post De-Dupe
32
Parcels with Zoning Table Joined
2044
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'Three Family', 'Four to Eight Units', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories            599
5          ht_conf       MAXHEIGHT              MEDIAN            599
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0    Brookline
1    Brookline
2    Brookline
3    Brookline
4    Brookline
5    Brookline
6    Brookline
7    Brookline
8    Brookline
9    Brookline
12816
11323
Total Rows in Roofprints
11323
Total Unique Parcel IDs
10712
10712
10712
10712
Rows in final join table for Building Structures
10712
Unique Parcels in Building Structures
10712
Rows in final parcel layer
12816
Unique Parcels in Final Parcel Layer
12816
Rows in overlap calc parcel layer
12816
Unique Parcels in overlap calc Parcel Layer
12816
12816
4481
4481
{'No Residential Uses Allowed', 'More than Eight Units'}
Parcel Rows
4481
Unique LOC_IDS
4481
Joined Parcel Length
5278
Split Zoned Parcels Detected
4481
Clean Join successful?
True
                LOC_ID ZO_CODE
626   F_748721_2968928   49C-1
629   F_748728_2968688   49C-1
635   F_748790_2967807   49C-1
630   F_748791_2968629   49C-1
634   F_749019_2968014   49C-1
...                ...     ...
3625  F_771481_2960116    49NP
3624  F_771595_2960268    49NP
3623  F_771899_2960183    49NP
3626  F_771903_2960719    49NP
3620  F_772181_2960548    49NP

[4481 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
254
Zoning Table post De-Dupe
52
Parcels with Zoning Table Joined
4481
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'More than Eight Units'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories            472
5          ht_conf       MAXHEIGHT              MEDIAN            472
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR           1887
9         gfa_conf         MAX_GFA            BLD_AREA              2

  Municipality
0    Cambridge
1    Cambridge
2    Cambridge
3    Cambridge
4    Cambridge
5    Cambridge
6    Cambridge
7    Cambridge
8    Cambridge
9    Cambridge
4768
3684
Total Rows in Roofprints
3684
Total Unique Parcel IDs
3608
3608
3608
3608
Rows in final join table for Building Structures
3608
Unique Parcels in Building Structures
3608
Rows in final parcel layer
4773
Unique Parcels in Final Parcel Layer
4769
Rows in overlap calc parcel layer
4773
Unique Parcels in overlap calc Parcel Layer
4769
4773
1524
1524
{'Four to Eight Units', 'Two Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Three Family'}
Parcel Rows
1524
Unique LOC_IDS
1524
Joined Parcel Length
1613
Split Zoned Parcels Detected
1524
Clean Join successful?
True
                LOC_ID ZO_CODE
976   F_777604_2967199   57NHR
977   F_777840_2967377   57NHR
987   F_778141_2967833   57NHR
1054  F_778280_2968267   57NHC
980   F_778284_2967395   57NHR
...                ...     ...
1575  F_787282_2971300    57R1
1585  F_787365_2971543    57R1
1586  F_787447_2971595    57R1
1583  F_787513_2971466    57R1
1607  F_787892_2971279     57W

[1524 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
27
Zoning Table post De-Dupe
16
Parcels with Zoning Table Joined
1524
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Four to Eight Units', 'Two Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Three Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories            226
5          ht_conf       MAXHEIGHT              MEDIAN            226
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0      Chelsea
1      Chelsea
2      Chelsea
3      Chelsea
4      Chelsea
5      Chelsea
6      Chelsea
7      Chelsea
8      Chelsea
9      Chelsea
7807
7663
Total Rows in Roofprints
7663
Total Unique Parcel IDs
7535
7535
7535
7535
Rows in final join table for Building Structures
7535
Unique Parcels in Building Structures
7535
Rows in final parcel layer
7854
Unique Parcels in Final Parcel Layer
7808
Rows in overlap calc parcel layer
7854
Unique Parcels in overlap calc Parcel Layer
7808
7854
1675
1675
{'Three Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Parcel Rows
1675
Unique LOC_IDS
1675
Joined Parcel Length
1768
Split Zoned Parcels Detected
1675
Clean Join successful?
True
                LOC_ID ZO_CODE
1755  F_772187_2976413   93ROD
1219  F_772704_2976365    93DD
86    F_772795_2975778    93DD
966   F_773028_2975574    93DD
965   F_773068_2975582    93DD
...                ...     ...
620   F_781539_2975451    93DD
1502  F_781706_2976554    93BD
1503  F_781847_2976514    93BD
1504  F_781962_2976606    93BD
1505  F_782076_2976668    93BD

[1675 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
14
Zoning Table post De-Dupe
13
Parcels with Zoning Table Joined
1675
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'No Residential Uses Allowed', 'More than Eight Units', 'Three Family', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',

c:\Users\ziacovino\Desktop\rightsizing-zoning-analysis\notebooks\..\src\features\nested_functions.py:309: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  mapc_lpd = pd.read_csv(muni_lpd_path)

23961
22872
Total Rows in Roofprints
22872
Total Unique Parcel IDs
22436
22436
22436
22436
Rows in final join table for Building Structures
22436
Unique Parcels in Building Structures
22436
Rows in final parcel layer
23962
Unique Parcels in Final Parcel Layer
23962
Rows in overlap calc parcel layer
23962
Unique Parcels in overlap calc Parcel Layer
23962
23962
1419
1419
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Parcel Rows
1419
Unique LOC_IDS
1419
Joined Parcel Length
1471
Split Zoned Parcels Detected
1419
Clean Join successful?
True
                LOC_ID ZO_CODE
1271  F_720525_2944452  207MR2
263   F_721277_2944553  207SR3
265   F_721288_2944374  207SR3
264   F_721413_2944656  207SR3
231   F_721757_2950333  207MR1
...                ...     ...
34    F_746521_2935659  207MR1
1441  F_746542_2935870  207MR1
33    F_746595_2935726  207MR1
37    F_746669_2935792  207MR1
404   F_748132_2944858  207SR1

[1419 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
2281
Zoning Table post De-Dupe
19
Parcels with Zoning Table Joined
1419
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE            231
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories             15
5          ht_conf       MAXHEIGHT              MEDIAN             15
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              3
9         gfa_conf         MAX_GFA            BLD_AREA              3

  Municipality
0       Newton
1       Newton
2       Newton
3       Newton
4       Newton
5       Newton
6       Newton
7       Newton
8       Newton
9       Newton
16355
15595
Total Rows in Roofprints
15595
Total Unique Parcel IDs
15295
15295
15295
15295
Rows in final join table for Building Structures
15295
Unique Parcels in Building Structures
15295
Rows in final parcel layer
16365
Unique Parcels in Final Parcel Layer
16356
Rows in overlap calc parcel layer
16365
Unique Parcels in overlap calc Parcel Layer
16356
16365
1417
1417
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Parcel Rows
1417
Unique LOC_IDS
1417
Joined Parcel Length
1418
Split Zoned Parcels Detected
1417
Clean Join successful?
True
                LOC_ID  ZO_CODE
1171  F_779417_2915118  243RESA
861   F_779420_2913850   243PUD
863   F_779732_2914866  243RESB
864   F_779954_2914458  243RESB
865   F_780269_2914400  243RESB
...                ...      ...
1070  F_804596_2923405  243RESA
1069  F_804780_2923400  243RESA
1009  F_804849_2924110  243BUSB
1010  F_804979_2924776  243RESA
1011  F_804999_2924831  243RESA

[1417 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
1934
Zoning Table post De-Dupe
12
Parcels with Zoning Table Joined
1417
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories             20
5          ht_conf       MAXHEIGHT              MEDIAN             20
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0       Quincy
1       Quincy
2       Quincy
3       Quincy
4       Quincy
5       Quincy
6       Quincy
7       Quincy
8       Quincy
9       Quincy

c:\Users\ziacovino\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: organizePolygons() received an unexpected geometry.  Either a polygon with interior rings, or a polygon with less than 4 points, or a non-Polygon geometry.  Return arguments as a collection.
  return ogr_read(
c:\Users\ziacovino\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\Lib\site-packages\pyogrio\raw.py:198: RuntimeWarning: Geometry of polygon of fid 12717 cannot be translated to Simple Geometry. All polygons will be contained in a multipolygon.
  return ogr_read(

12660
10434
Total Rows in Roofprints
10434
Total Unique Parcel IDs
10350
10350
10350
10350
Rows in final join table for Building Structures
10350
Unique Parcels in Building Structures
10350
Rows in final parcel layer
12660
Unique Parcels in Final Parcel Layer
12660
Rows in overlap calc parcel layer
12660
Unique Parcels in overlap calc Parcel Layer
12660
12660
1543
1543
{'Four to Eight Units', 'Two Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Single Family'}
Parcel Rows
1543
Unique LOC_IDS
1543
Joined Parcel Length
1672
Split Zoned Parcels Detected
1543
Clean Join successful?
True
                LOC_ID ZO_CODE
70    F_782424_2976263   248RB
127   F_782532_2976955   248RB
432   F_782779_2977793   248NB
433   F_782960_2978136   248NB
75    F_783130_2976331   248RB
...                ...     ...
1416  F_800446_2985621   248RA
1419  F_800528_2985654   248RA
1399  F_800569_2985781   248RA
1406  F_801602_2986210   248RA
1407  F_801620_2986251   248RA

[1543 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
141
Zoning Table post De-Dupe
19
Parcels with Zoning Table Joined
1543
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Four to Eight Units', 'Two Family', 'No Residential Uses Allowed', 'More than Eight Units', 'Single Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories             30
5          ht_conf       MAXHEIGHT              MEDIAN             30
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0       Revere
1       Revere
2       Revere
3       Revere
4       Revere
5       Revere
6       Revere
7       Revere
8       Revere
9       Revere
12592
11946
Total Rows in Roofprints
11946
Total Unique Parcel IDs
11681
11681
11681
11681
Rows in final join table for Building Structures
11681
Unique Parcels in Building Structures
11681
Rows in final parcel layer
12595
Unique Parcels in Final Parcel Layer
12593
Rows in overlap calc parcel layer
12595
Unique Parcels in overlap calc Parcel Layer
12593
12595
4432
4432
{'Three Family', 'No Residential Uses Allowed', 'More than Eight Units'}
Parcel Rows
4432
Unique LOC_IDS
4432
Joined Parcel Length
5269
Split Zoned Parcels Detected
4432
Clean Join successful?
True
                LOC_ID  ZO_CODE
2734  F_755002_2972459    274UR
1802  F_755066_2972566    274UR
1790  F_755107_2972614    274NR
2824  F_755116_2972343    274UR
2043  F_755162_2973057    274UR
...                ...      ...
3934  F_770103_2965687    274UR
1660  F_770108_2968839  274ASMD
1664  F_770125_2967748  274ASMD
3935  F_770130_2965797    274UR
1662  F_770141_2968429  274ASMD

[4432 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
1416
Zoning Table post De-Dupe
17
Parcels with Zoning Table Joined
4432
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'No Residential Uses Allowed', 'Three Family', 'More than Eight Units'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories            210
5          ht_conf       MAXHEIGHT              MEDIAN            210
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              5
9         gfa_conf         MAX_GFA            BLD_AREA              5

  Municipality
0   Somerville
1   Somerville
2   Somerville
3   Somerville
4   Somerville
5   Somerville
6   Somerville
7   Somerville
8   Somerville
9   Somerville
7624
7603
Total Rows in Roofprints
7603
Total Unique Parcel IDs
7348
7348
7348
7348
Rows in final join table for Building Structures
7348
Unique Parcels in Building Structures
7348
Rows in final parcel layer
7627
Unique Parcels in Final Parcel Layer
7625
Rows in overlap calc parcel layer
7627
Unique Parcels in overlap calc Parcel Layer
7625
7627
1225
1225
{'Single Family', 'No Residential Uses Allowed', 'Three Family', 'Two Family'}
Parcel Rows
1225
Unique LOC_IDS
1225
Joined Parcel Length
1553
Split Zoned Parcels Detected
1225
Clean Join successful?
True
               LOC_ID    ZO_CODE
1078  M_223684_901974  314PSCD-1
1060  M_223730_901787  314PSCD-3
1059  M_223763_901824  314PSCD-3
1077  M_223846_902223  314PSCD-1
1072  M_223863_901931  314PSCD-1
...               ...        ...
860   M_228885_902424       314T
1367  M_228911_901598     314I-3
1366  M_229043_901667     314I-3
1329  M_229163_901752    314R1.2
1328  M_229283_901779    314R1.2

[1225 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
140
Zoning Table post De-Dupe
21
Parcels with Zoning Table Joined
1225
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'Single Family', 'No Residential Uses Allowed', 'Three Family', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories             30
5          ht_conf       MAXHEIGHT              MEDIAN             30
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0    Watertown
1    Watertown
2    Watertown
3    Watertown
4    Watertown
5    Watertown
6    Watertown
7    Watertown
8    Watertown
9    Watertown
4523
4342
Total Rows in Roofprints
4342
Total Unique Parcel IDs
4236
4236
4236
4236
Rows in final join table for Building Structures
4236
Unique Parcels in Building Structures
4236
Rows in final parcel layer
4525
Unique Parcels in Final Parcel Layer
4524
Rows in overlap calc parcel layer
4525
Unique Parcels in overlap calc Parcel Layer
4524
4525
529
529
{'No Residential Uses Allowed', 'Two Family'}
Parcel Rows
529
Unique LOC_IDS
529
Joined Parcel Length
558
Split Zoned Parcels Detected
529
Clean Join successful?
True
              LOC_ID ZO_CODE
83   M_241481_902590   346RA
81   M_241505_902761   346RA
82   M_241536_902616   346RA
29   M_241552_902504   346RA
84   M_241709_902591   346RA
..               ...     ...
61   M_243817_902309   346RA
484  M_243830_904303   346RA
11   M_243839_902235   346RA
482  M_243839_904418   346RA
12   M_243849_902221   346RA

[529 rows x 2 columns]
Any Parcels missing a Zone Code?
0
Same parcels we started with?
True
Same number of parcels we started with?
True
Zoning Table pre-dedupe
7
Zoning Table post De-Dupe
7
Parcels with Zoning Table Joined
529
Zones assigned to Parcels by Largest Share
LOCIDs of Parcels without Zoning
set()
{'No Residential Uses Allowed', 'Two Family'}
Index(['LOC_ID', 'geometry', 'Unnamed: 0', 'TOWN_ID', 'PROP_ID', 'BLDG_VAL',
       'LAND_VAL', 'OTHR_VAL', 'TOTAL_VAL', 'FY', 'LOT_SIZE', 'LS_DATE',
       'LS_PRICE_S', 'LS_PRICE_L', 'LUC_L', 'MIN_LUC', 'MAX_LUC', 'LUCA_L',
       'MIN_LUCA', 'MAX_LUCA', 'LUC_DES_L', 'LUCA_DES_L', 'LUCA_SYMB',
       'SITE_ADR_L', 'SITE_ADR_M', 'ADR_NUM', 'FULL_STR', 'LOCATION', 'CITY',
       'ZIP', 'OWNER1', 'OWN_ADR', 'OWN_CITY', 'OWN_STATE', 'OWN_ZIP',
       'OWN_CO', 'LS_BOOK', 'LS_PAGE', 'REG_ID', 'ZONING_L', 'ZONING_M',
       'YEAR_BUILT', 'BLD_AREA', 'UNITS', 'UNITS_CNDO', 'RES_AREA', 'STYLE',
       'NUM_ROOMS', 'LOT_UNITS', 'STORIES', 'MA_PROP_ID', 'CAMA_ID',
       'MN_STD_DES', 'MN_USE_DES', 'MUNI.USE_CODE_underlying.x', 'MX_STD_DES',
       'MX_USE_DES', 'MUNI.USE_CODE_underlying.y', 'LOT_SIZE_G', 'ADR_PNTS',
       'IMP_UNITS', 'FAR', 'FAR_FLAG', 'BLDGV_PSF', 'BLDLND_RAT', 'LOC_ID_bld',
       'MEDIAN_stories', 'MEDIAN', 'ftpt_area', 'par_lot_cov_pct', 'DUA',
       'LPU', 'ZO_CODE', 'oid_', 'zo_code', 'muni_id', 'muni', 'zo_abbr',
       'zo_name', 'ZO_NAME', 'MUNI_ID', 'MUNI', 'ZO_AldUse', 'ZO_ABBR',
       'ZO_USETY', 'ZO_USEDE', 'MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'MAXFLRS',
       'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA'],
      dtype='object')
0
LOT_SIZE
par_lot_cov_pct
LOT_SIZE_G
MIN_LUCA
MEDIAN_stories
MEDIAN
IMP_UNITS
DUA
FAR
BLD_AREA
  Conformity Field Zoning Measures Existing Conditions  Missing Count  \
0          ls_conf      MINLOTSIZE            LOT_SIZE              0
1          lc_conf       PCTLOTCOV     par_lot_cov_pct              0
2          ld_conf           LApDU          LOT_SIZE_G              0
3          lu_conf       ZO_AldUse            MIN_LUCA              0
4          fl_conf         MAXFLRS      MEDIAN_stories              9
5          ht_conf       MAXHEIGHT              MEDIAN              9
6          du_conf           MAXDU           IMP_UNITS              0
7         dua_conf           DUpAC                 DUA              0
8         far_conf          MAXFAR                 FAR              0
9         gfa_conf         MAX_GFA            BLD_AREA              0

  Municipality
0     Winthrop
1     Winthrop
2     Winthrop
3     Winthrop
4     Winthrop
5     Winthrop
6     Winthrop
7     Winthrop
8     Winthrop
9     Winthrop

In [ ]:
muni_test_merge_full

Structure Merge Fixing

In [3]:
town_name = 'Somerville'
muni_parcels = get_landuse_data(town_name)
muni_parcels = muni_parcels[muni_parcels[units]> 2]
from src.features.indicator_functions import *
roofprints_gdf = ldr_bld[ldr_bld['CITY'] == town_name].copy()
roofprints_gdf['ftpt_area'] = roofprints_gdf.area

In [4]:
overlap_test = overlap_stats(layer_1 = roofprints_gdf,
                             layer_2 = muni_parcels,
                             stats = 'maj',
                             id_field = 'STRUCT_ID', 
                             stats_field = 'LOC_ID',
                             new_field_name = 'LOC_ID2',
                             normalize = False)

In [ ]:
overlap_test

In [ ]:
roofprints_gdf[roofprints_gdf['LOC_ID_bld'].isna()]


sliced = overlap_test[['STRUCT_ID','LOC_ID_bld', 'LOC_ID2_maj' ]]

Empty GeoDataFrame
Columns: [STRUCT_ID, LOC_ID_bld, Min_LUC_Assign, SITE_ADDR_L, CITY, MAX, MEAN, MEDIAN, PCT90, PCT75, PCT25, MAX_stories, MEAN_stories, MEDIAN_stories, PCT75_stories, PCT25_stories, roof_sqm, flat_roof, primary_structure, geometry, ftpt_area]
Index: []

[0 rows x 21 columns]

In [59]:
col_name = ['PCTLOTCOV', 'ZO_NAME', 'ZO_AldUse']
nas = []
for x in col_name:
    na_count = len(res_zoning[res_zoning[x].isna()])
    nas.append(na_count)


print(nas)

[558, 0, 0]

In [29]:
all_measure_fields = res_zoning.columns.to_list()[18:27]
all_measure_fields.insert(3, "ZO_AldUse")

print(all_measure_fields)

['MINLOTSIZE', 'PCTLOTCOV', 'LApDU', 'ZO_AldUse', 'MAXFLRS', 'MAXHEIGHT', 'MAXDU', 'DUpAC', 'MAXFAR', 'MAX_GFA']

In [7]:
import numpy as np
town_name = 'Lynn'
all_conf_fields = ['ls_conf', 'lc_conf', 'ld_conf', 'lu_conf', 'fl_conf', 'ht_conf', 'du_conf', 'dua_conf', 'far_conf','gfa_conf']


d1 = dict.fromkeys(all_conf_fields, np.sum)
d2 = dict.fromkeys(['LOC_ID'], 'count')
d = d1 | d2

In [5]:
print(d)

{'ls_conf': 'sum', 'lc_conf': 'sum', 'ld_conf': 'sum', 'lu_conf': 'sum', 'fl_conf': 'sum', 'ht_conf': 'sum', 'du_conf': 'sum', 'dua_conf': 'sum', 'far_conf': 'sum', 'gfa_conf': 'sum', 'LOC_ID': 'count'}

In [ ]:


rz_gdb = r"\\Data-Sync\Public\DataServices\Projects\Current_Projects\Housing\Zoning-to-Built-Form\Rightsizing Zoning\Rightsizing Zoning.gdb"
# base_zone_summary = gpd.read_file(rz_gdb, layer= "mmc_base_zone_scores")
# base_zone_summary_muni = base_zone_summary[base_zone_summary['CITY'] == town_name]

base_parcel_scores = gpd.read_file(rz_gdb, layer= "mmc_base")
base_parcel_scores_muni = base_parcel_scores[base_parcel_scores['CITY'] == town_name]

# overlay_zone_summary = readzonesummary
# parcel_summary = readparceloutputs

#1 Which Zoning Standards lead to the most non-conformity?
analysis_1 = base_parcel_scores_muni[all_conf_fields + ['LOC_ID'] + ['ZO_CODE']]

summary = analysis_1.groupby('ZO_CODE').agg(d).reset_index()

In [13]:
summary = analysis_1.groupby('ZO_CODE').agg(d)


summary_pct = summary.apply(summary/summary['LOC_ID'], axis = 1)

SpecificationError: nested renamer is not supported

In [41]:
all_conf_fields = ['ls_conf', 'lc_conf', 'ld_conf', 'lu_conf', 'fl_conf', 'ht_conf', 'du_conf', 'dua_conf', 'far_conf','gfa_conf']

SyntaxError: invalid syntax (2853968472.py, line 3)

In [65]:
from src.features.zoning_nonconformity_scripts import analysis_outputs
analysis_test = analysis_outputs('Melrose')

analysis_test

ls_conf
ls_conf
lu_conf
nan

,Analysis Concept,Total Conformity,Lot Size,Building Shape,Unit Density
0,Zoning Standard with most Nonconformity,ls_conf,ls_conf,lu_conf,NaN
1,Average Effect of Overlay Zoning,NaN,NaN,NaN,NaN
2,Correlation Score: Year Built,-0.055445,-0.127576,0.037944,NaN
3,Correlation Score: Lot Size,-0.002772,-0.213389,0.190018,NaN

In [64]:
analysis_test

{'Analysis Concept': {'Average Effect of Overlay Zoning',
  'Correlation Score: Lot Size',
  'Correlation Score: Year Built',
  'Zoning Standard with most Nonconformity'},
 'Total Conformity': {-0.0027718913832963563,
  -0.055445195936244494,
  'ls_conf',
  nan},
 'Lot Size': {-0.12757562866599645, -0.2133890377242767, 'ls_conf', nan},
 'Building Shape': {0.03794405511641818, 0.1900178542482494, 'lu_conf', nan},
 'Unit Density': {nan, nan, nan}}

In [52]:
analysis_test[all_conf_fields].max(skipna= True)

ls_conf     1.00
lc_conf     1.00
ld_conf     1.00
lu_conf     1.00
fl_conf     1.00
ht_conf     1.00
du_conf      NaN
dua_conf     NaN
far_conf    0.82
gfa_conf     NaN
dtype: float64

In [31]:
analysis_test['ls_conf_pct'] = analysis_test['ls_conf']/analysis_test['LOC_ID']

print(analysis_test)

         ls_conf  lc_conf  ld_conf  lu_conf  fl_conf  ht_conf  du_conf  \
ZO_CODE
178BA-1     32.0      NaN      NaN     28.0      4.0      4.0      NaN
178BA-2     39.0      NaN      NaN     24.0      6.0      6.0      NaN
178BB        0.0      1.0      NaN      NaN      1.0      1.0      NaN
178BB-1     15.0     27.0      NaN      NaN     27.0     27.0      NaN
178BD       15.0      3.0      NaN     17.0      2.0      2.0      NaN
178I-A       0.0      4.0      NaN      4.0      4.0      4.0      NaN
178SR-A      1.0      0.0      NaN      2.0      0.0      1.0      NaN
178SR-B      4.0      4.0      NaN      4.0      0.0      0.0      NaN
178UR-A    222.0    330.0    366.0    366.0    153.0    162.0      NaN
178UR-B    256.0    288.0      NaN    312.0    116.0    132.0      NaN
178UR-C    160.0    300.0      NaN    190.0     15.0     20.0      NaN
178UR-D     10.0      1.0      NaN      7.0      1.0      1.0      NaN

         dua_conf  far_conf  gfa_conf  LOC_ID  ls_conf_pct
ZO_CODE
178BA-1       NaN      44.0       NaN      54     0.592593
178BA-2       NaN      42.0       NaN      66     0.590909
178BB         NaN       0.0       NaN       1     0.000000
178BB-1       NaN       0.0       NaN      27     0.555556
178BD         NaN      18.0       NaN      24     0.625000
178I-A        NaN       0.0       NaN       4     0.000000
178SR-A       NaN       0.0       NaN       2     0.500000
178SR-B       NaN       0.0       NaN       4     1.000000
178UR-A       NaN       0.0       NaN     366     0.606557
178UR-B       NaN       0.0       NaN     312     0.820513
178UR-C       NaN     225.0       NaN     325     0.492308
178UR-D       NaN      18.0       NaN      22     0.454545

In [13]:
from src.features.nested_functions import *
from src.data.make_dataset import luc_adjusted
cambridge = get_landuse_data("Cambridge")

print(set(cambridge['LOT_SIZE_G']))

{32802.0594110011, 50.1570637447751, 51.3637700880609, 60.9053233911055, 65.2951935868858, 95.1206936176864, 97.4263041242139, 163938.648607354, 130.037114348806, 132.297441308768, 138.436343427934, 144.541715906049, 145.609661158357, 147.653069104161, 159.164319238532, 170.70464254932, 175.411250419021, 184.394009355273, 189.852269851489, 190.742380816434, 192.87601890651, 195.23507220484, 200.145218467748, 202.022405429217, 213.799457980423, 219.483790369105, 220.016266340339, 237.770669462678, 33031.6693704175, 270.89345491152, 282.493356457734, 302.340058886697, 33076.4037018669, 313.206200770408, 33090.0297937479, 328.481835380884, 164171.226607436, 332.057235627356, 65867.8299939334, 336.046505891331, 336.018936294749, 349.209195007819, 351.035167664433, 356.050491039644, 362.625574383506, 403.877310981483, 409.499877131766, 411.775806913685, 2982301.83220525, 423.063607370528, 426.09808147082, 435.886402699384, 447.829601317766, 450.509546436249, 480.435529448954, 295400.761014895, 489.126157600808, 488.697756953607, 488.925728385546, 500.47936412249, 504.12067378899, 505.112081812152, 505.627684686115, 513.255544923182, 514.384594737322, 523.129224335629, 528.440430996769, 552.974655046065, 578.250588663734, 578.173839152549, 582.688532294752, 33350.8346057347, 590.687436045273, 590.722934931671, 612.098712081794, 623.644439080911, 625.677881289474, 628.004880272948, 629.251917947377, 634.359866178105, 636.819558263684, 197252.076207654, 650.955831337332, 650.497117593407, 654.002688157145, 661.757673020931, 33430.0497191968, 685.748482829245, 689.043922570716, 696.696399353728, 697.254112668581, 700.425360600109, 701.479425429203, 717.273262550393, 717.579970756782, 722.087106217365, 735.597715517487, 743.73808943413, 745.588090583902, 749.803179549494, 750.694058463708, 754.864911017916, 756.562500247147, 760.000082143485, 760.268742088162, 33531.6001879867, 765.993355732495, 769.49993647405, 769.510536442419, 769.540171772881, 773.539982992639, 775.184301087004, 782.425689091459, 783.407179098033, 782.870964206117, 790.429133802114, 792.12961297095, 792.565195118617, 794.191427561837, 799.118971748251, 800.886688045736, 99105.6089285557, 802.335793346014, 803.537524649733, 804.922832312902, 805.739682712546, 805.799381277566, 811.521901504259, 812.417783546253, 812.716782056571, 66350.1278609913, 817.597874627109, 819.578370875658, 819.160843605662, 819.707226186708, 822.795146452655, 831.60094189444, 831.326624790404, 833.73339095294, 835.754635047819, 835.346456163057, 837.105314959646, 837.860974459455, 839.661670593913, 842.379251611387, 843.847041173064, 843.091650371764, 845.154859409277, 846.205921321487, 853.036393951355, 857.631922224035, 859.40934957866, 860.438648270588, 864.357359898351, 864.83464764512, 869.836115561724, 871.678811119383, 872.981835316959, 873.116437856049, 1311595.39160495, 876.411087419634, 33647.0854684185, 884.76940647492, 99189.2875947021, 886.699827407601, 886.338727670699, 884.52884514917, 889.738897801246, 889.999261426365, 891.711532184204, 890.915705781244, 890.482640637343, 894.4990157229, 894.094283164859, 896.434046606923, 896.831418272056, 899.288680521375, 901.176589315208, 904.931263792246, 66444.3872746601, 908.387795055587, 913.025359663252, 913.942462111113, 913.202489956056, 917.788139517558, 919.980643412935, 920.478715334574, 922.555438158206, 928.375442395725, 929.742371929698, 930.955463094225, 932.709145128027, 933.662167829827, 934.607744390156, 936.043032256664, 937.75178757479, 937.219199741992, 939.12850633094, 940.550656009973, 940.258645976596, 941.583415841408, 943.654847020913, 944.516322031128, 940.140106414079, 947.689318542674, 947.253444868126, 949.295694549925, 951.223178858883, 955.318796433696, 955.607956130094, 958.025580070991, 959.00811988213, 960.713828724133, 960.581128443893, 962.832000833527, 959.570250542408, 961.791789630561, 966.465305447101, 6705.37674718744, 967.267765730988, 968.912535964409, 970.560531546068, 971.725639545499, 974.544885012945, 976.448299136913, 977.648509004036, 981.585178483572, 982.29318152134, 983.517511646927, 984.778010012422, 986.761426211626, 986.76524456531, 989.328248400593, 993.469732283767, 997.974843667059, 999.655978701665, 1000.85068030511, 1001.86638800872, 1002.72650116918, 1001.73421570575, 1002.3242182798, 1005.58784426833, 1006.52102758825, 1004.37291179878, 1003.76461642782, 1006.63422689292, 1009.07664162197, 1011.64405008481, 1012.40275461594, 1012.3190209118, 1020.07295743008, 1020.22588582426, 1023.22480291965, 1024.16676718188, 1025.54279665829, 1026.07234245714, 1027.7238079972, 1026.97502457551, 1026.52060363236, 1031.94581567647, 1032.5605423616, 1033.78223414587, 1038.47469305899, 1039.29195384116, 1038.50762781563, 1039.50147424732, 1042.46899019668, 1042.28314110404, 1045.7068162402, 1046.29515330744, 1050.62930592654, 33819.5412476721, 1052.81319736741, 1050.02128449816, 1054.18799220199, 1055.65191220145, 1055.99261822903, 1050.10953894284, 1057.69438984384, 1059.01612529706, 1061.89472117382, 1061.84912474453, 1066.56358604155, 1067.99036478349, 1068.47957710281, 1070.95009035367, 1070.46373438754, 1073.98133276637, 1075.37668747158, 1075.19754789806, 1076.29466081054, 1078.55357923294, 1079.44561969737, 1080.13628630988, 1079.80150934118, 1082.72223613053, 1079.35654488423, 1084.04963060113, 1085.68526707153, 1085.56364771401, 1083.94213374807, 1088.29757209051, 1089.05733263006, 1088.05497880306, 1085.93145996678, 1092.75013845512, 1084.78608965457, 1089.13123573566, 1099.87676310388, 1100.04131170934, 1101.70312737598, 1101.71564373285, 1103.74692243737, 1102.45360820189, 1105.61283129002, 1106.93730499921, 1106.98966862317, 1106.58787506149, 1105.03047007902, 1104.20154218795, 1111.31873385085, 1112.31178495476, 1112.22786993467, 1114.12500012534, 33874.8232968596, 1116.30807105681, 1118.79088789285, 1119.78112702311, 1119.31865140514, 1122.90969465927, 1123.14320868048, 1124.62116519322, 1124.62861053898, 1126.56803589495, 1124.69582569355, 1128.0605315258, 1129.1130581904, 1130.70708296688, 1129.33870753676, 1128.26033463696, 1133.62947170727, 66664.1615193057, 1142.05462556756, 1144.14271566368, 1146.44697356986, 1147.95808766375, 1150.92462296093, 1150.4459074915, 1153.9275525475, 1154.78949355808, 1153.7971618347, 1153.05339523355, 1154.52306534082, 1159.3583088315, 1159.82295684068, 1161.76062188574, 1161.43705471214, 1163.21981620042, 1160.89084995433, 1165.11191782304, 1161.3853000154, 1165.18327584811, 1168.26111016423, 1169.94066719199, 1161.67078867243, 1170.34470477678, 1172.96805294729, 1173.26275868691, 1173.8267234693, 1175.07344836063, 1176.60440518547, 1177.32472098376, 1172.47696056825, 1174.97576274141, 1180.25672670881, 1181.86550694946, 1182.21062812009, 1175.94315979392, 1176.65873317581, 1185.88034347002, 1186.53859113931, 1187.00267712072, 1187.40059048032, 1185.67962621348, 1190.85806302268, 1191.76094120313, 1190.24730132887, 1193.63547841866, 1193.52625086991, 1193.69764125093, 1194.36727765397, 1197.93750015194, 1198.56360750972, 1199.93747575871, 1199.75300201444, 1201.77571379401, 1202.1112733269, 1202.48634354237, 1204.72102568795, 1201.50633374107, 1206.24237135336, 1207.18323460672, 1204.0583219686, 1209.70103352693, 1212.97719843505, 1212.3349802941, 1213.15136157602, 1212.13533435414, 1213.90229489154, 1217.56742151807, 1215.17273571151, 1212.97945348894, 1220.61232811862, 1221.44069890792, 1222.46251624985, 1223.22121073461, 1224.46875000928, 1222.62586120694, 1225.0575798545, 1220.72170252257, 1221.58625002888, 1229.97834168511, 1229.22063107366, 1231.06778370202, 1229.31859532803, 1231.35260821129, 1232.17453225461, 1235.61934024193, 1236.39889326701, 1237.84980983205, 1237.14724659531, 1230.48348320632, 1233.9713335122, 1241.27204818543, 1242.03567408248, 1243.35406693592, 1244.33817147708, 1244.02972422555, 1246.05224896352, 1247.77079211181, 1248.64050158246, 1249.78395692027, 1250.13287369398, 1251.34633523853, 1252.62130914409, 1253.16629888911, 1247.7211287937, 1255.1056433549, 1255.93238034307, 1257.33230815566, 1255.24241174446, 1259.72502775048, 1253.71710942059, 1252.04105581116, 1261.36899711248, 1263.37879829175, 1264.01349284186, 1265.30889110091, 1266.30139459173, 1265.14530054811, 1266.64572183905, 1269.51920021325, 1268.59670309363, 1271.37081692425, 1272.14720615321, 1272.1928261364, 1269.2381882706, 1275.25213294646, 230649.820673551, 1280.95976800757, 1281.58132393648, 1282.62219411194, 1283.23831210166, 1283.85304253476, 1283.38336533347, 1283.03059736901, 1286.40391853409, 1286.37273816284, 1289.40840102392, 1290.8306586585, 1291.70194363836, 1291.97305569631, 1288.86328864942, 1294.02857364887, 1288.00196845117, 1291.21616662716, 1297.95866113995, 1298.04765429555, 1299.27503956704, 1299.79573201569, 1301.10340554168, 1295.95800551632, 1303.49760665054, 1304.49499693915, 6772.183274537, 1306.60403172034, 1304.64743255802, 1308.12153689916, 1304.69590624476, 1309.94824626749, 1311.78866255223, 1312.13793774624, 1313.43015775548, 1314.23458024062, 1315.55972177331, 1312.2811940492, 1316.06045144512, 1318.99122384283, 1318.9159682159, 1320.96109407914, 1320.28548478365, 1317.92195199945, 1323.48366632906, 1324.70017230633, 1325.6259842372, 1326.88513586669, 1325.07016141366, 1328.59986084816, 1329.48572826963, 1328.42495262588, 1331.27839194566, 1332.81633519392, 1331.69501869727, 1333.59605627371, 1335.12573810018, 1336.7265009581, 1336.19713732415, 1338.08196522497, 1338.59596442579, 1340.95308455871, 1341.10294409105, 1340.07915039617, 1340.72199102137, 1344.74709752265, 1344.62762520193, 1345.53205719303, 1341.4445850052, 1348.92236663754, 1349.07997003913, 1350.73326789373, 1351.20127914368, 1352.28527281923, 1349.38371560197, 1349.13385776342, 1352.39552041728, 1356.24275012849, 1357.94923905669, 34126.6792423433, 1359.57086808732, 1360.76021145563, 34129.3131493144, 1362.0634655188, 1363.25906171871, 1364.60110221037, 1362.4822084182, 1358.35511411979, 1367.54839233, 1367.86663353159, 1369.40723428379, 1369.66762200759, 1370.66164689193, 1371.88432693704, 1373.88969971214, 1374.68397292359, 1375.35822635531, 1374.95894850523, 1375.25331348523, 1378.15809477196, 1376.99030328981, 1374.08957866078, 1378.09744119114, 1382.34233421967, 1374.45365780342, 1384.8772149871, 1385.91322156162, 1381.3084394142, 1386.81914450475, 1382.99015777199, 1389.84548830378, 1389.72293333353, 1390.77940474117, 1392.97513665848, 1392.78572018132, 1394.73250774562, 1391.61723638744, 1392.39800704812, 1389.01328762585, 1390.02858814166, 1398.1541366227, 1400.74190944638, 1401.08874639403, 1402.33023160835, 1402.22453261049, 1404.38853345796, 1405.87928559334, 1406.13225820924, 1402.73410910128, 1408.40962355805, 1408.02745755974, 1410.29945868478, 1411.00399967637, 1412.95451064644, 1412.02608242965, 34182.08309971, 1415.30252572731, 1412.29632474731, 1416.00698906826, 1412.02190271157, 1419.7243275795, 1417.08523158466, 1421.08335790817, 1421.83325074035, 1421.94619396413, 1418.11110877182, 1419.11164008136, 1419.47271660926, 1422.33706985747, 1424.58896029758, 1429.67660824439, 1430.63640042601, 1426.01237352107, 1432.05160308749, 1432.78358770014, 1434.18642206635, 1432.2941950451, 1436.81645130543, 1434.56303079466, 1432.48895105526, 1441.65657840441, 1442.3377309872, 1441.82782798577, 1444.66646180166, 1443.16591189611, 1446.55216519975, 1447.93832025415, 1448.16875851403, 1447.57157911542, 1446.86007199611, 1446.30094429078, 1446.75241187888, 1449.38482210806, 1447.84895850856, 1450.60336741635, 1454.75065619123, 1457.63631930643, 1457.54207713067, 1454.83404165015, 1453.42975514573, 1461.14852438469, 1461.01574786242, 1463.57037790842, 1463.0740649865, 1461.79958617478, 1466.38942571477, 1467.4333170315, 1467.62967509996, 1463.02672370716, 1468.96185355946, 1471.31434554845, 1472.22933081612, 1472.67126523192, 1469.88987714897, 1475.47111180215, 1475.14859944164, 1477.05112813803, 1477.28577833278, 1478.68896086018, 1480.85131955528, 1478.56419507405, 1480.8186505997, 1483.17408974035, 1483.11745376424, 1485.00783291469, 1486.33021509918, 1484.14999577019, 1488.72896168453, 1484.96961084144, 1490.53805709695, 1484.22399926474, 1492.48907482236, 1493.78412036254, 1494.74101884436, 1495.57000466769, 1496.11593623652, 1497.22219998952, 1497.32257864872, 1494.19131448179, 1500.5305085873, 1501.35159282165, 1501.96892770984, 1503.82393169386, 1503.59883510279, 1501.69426706278, 1503.59471300872, 1502.08333013189, 1500.06680633784, 1509.12774776087, 1503.59863775582, 1511.39452365445, 1512.07252288487, 1513.55647144221, 1512.18700961732, 1509.31003990617, 1516.95367571443, 1513.64400598631, 1518.05223903227, 1519.92589341544, 1519.83970785475, 1521.44826950021, 1518.62754287663, 1523.09219182801, 1521.06204953418, 1525.04847483847, 1526.47752624829, 1527.726685791, 1528.8276835079, 1525.41285296666, 1530.31397649434, 1531.18406515905, 1532.91497667187, 1533.5944132707, 1534.76377976051, 1534.44020270101, 1536.33753662533, 1537.81881550196, 1538.96274343104, 1536.81620111053, 1538.73016318116, 1539.41170422112, 1534.83066778596, 1539.53072700748, 1538.06450859898, 1538.50467512912, 1542.46099803904, 1542.59652413262, 1548.66301713421, 1548.24132101946, 1549.12071766409, 1551.46026095119, 1550.40871133457, 1553.74641715115, 1554.38591760833, 1553.83612162746, 1555.59487824084, 1553.94229915167, 1558.49206397652, 1559.21750307148, 1559.89677640155, 1561.20895819392, 1561.31456887207, 1563.26425615849, 1564.87376989943, 1565.98228330084, 1562.56841868318, 1567.4917707799, 1567.28781173607, 1569.2972438473, 1566.1979761762, 1571.22229769393, 1572.17568950167, 1566.21003477589, 1574.16683097137, 1566.77622546552, 1573.44853175392, 1574.86134927383, 1574.67999495452, 1579.28916754553, 1580.71166091154, 1580.35297717528, 1580.13353034817, 1583.94179880153, 1583.66190920527, 1585.61132579137, 1582.15100074388, 1587.4624750782, 1587.42445886129, 1584.18257834686, 1583.1650312762, 1591.77362230994, 1592.68516308815, 1592.00909440098, 1594.55788658036, 1592.96013831571, 1596.59334040696, 1597.37303090108, 1597.06712219422, 1597.89489750573, 1600.31357530179, 1597.80428145774, 34370.5868585482, 1602.50639803658, 1604.02829710716, 1605.55761540422, 1606.09181738288, 1606.52365195356, 1607.76171508575, 1607.30101727895, 1606.33538925038, 1611.59775810234, 1603.11433732091, 1605.62286742148, 1609.63431970915, 1615.37911994305, 1612.30241119155, 1617.91584051674, 1617.47883864234, 1617.52557155233, 1620.66791205476, 1621.70241169869, 1618.3142637594, 1623.73212227498, 1623.63446153841, 1623.01824833169, 1626.96591965188, 1621.32146433837, 1622.10125151474, 1629.17908320128, 1623.07678535041, 1622.94851287132, 1632.21401273812, 1633.17187489455, 1634.70722614681, 1632.80786949936, 1636.09729889157, 1636.00579866462, 1635.59190467593, 1634.07070202015, 1632.33800893302, 1641.18036400926, 1641.46576501491, 1635.65390719551, 1644.593340312, 1643.40991398979, 1646.9097161792, 1647.8217448482, 1647.65981786415, 1649.98205091535, 984686.680776101, 1647.29241188787, 1652.32598937204, 1652.53834515132, 1654.59853364247, 99959.7383828719, 1656.68133864621, 1657.21736612029, 1651.87766099675, 1652.40514310848, 1660.60111456716, 1661.98849762706, 1661.40965385334, 1661.53786432731, 1664.82332698095, 1665.4234760764, 1666.73321884021, 1667.21911882783, 1666.05565158758, 1669.42433608307, 1670.71600257921, 1671.27961744665, 1672.30477846116, 1671.18097875611, 1672.66508523986, 1671.58608462669, 1674.60843995898, 1677.1716387635, 1678.97983823332, 1678.53657917245, 1678.08345646514, 1678.5580602054, 1679.96678191343, 1677.71665908048, 1684.42158841679, 1685.56536233495, 1684.11318868189, 1687.81846646783, 1684.66393891825, 1687.1739661329, 1690.46489541039, 1691.86474182514, 1692.31684758578, 1691.46120371062, 1694.0978512327, 1691.24101843729, 1692.55807076831, 1697.87602063335, 1696.40252778096, 1699.59137550119, 1697.66465753445, 1701.66240068348, 1695.19845006913, 1703.5089819096, 1704.9945119913, 1703.68546821856, 1706.38548863605, 1699.02899437415, 1700.06397568779, 1709.01975081146, 1710.77727368389, 1711.46438960555, 1712.34427474121, 1713.23262931188, 1713.86173930131, 34480.5159933902, 1711.1640419328, 1717.55150929738, 1718.1596489605, 1718.53763146747, 1720.63424642187, 1720.19378206466, 1716.32031238028, 1723.9107135084, 1720.90238855273, 1725.2748519924, 1726.16819964801, 1727.87044794627, 1728.5437252355, 1729.06877426815, 1727.51629858417, 1728.21450623254, 1728.74122331727, 1732.13387695726, 1734.21036466629, 1733.58822344467, 1736.8636805545, 1736.61622419398, 1729.15828975995, 1738.05868597883, 1738.80275839516, 1741.56839525222, 1741.24257719619, 1742.52167581178, 1744.85162446907, 1744.71678129802, 1745.99478174877, 1747.10290333318, 1747.10515819645, 1749.99114470995, 1746.35433116721, 1751.78384057207, 1746.18532677453, 1753.85297754663, 1753.79071489423, 1755.87781231068, 1756.75000019527, 1757.68142118461, 1758.75012391478, 1759.80634776266, 1756.0071883214, 1761.30987548119, 1758.69200749092, 1763.54199459276, 1764.45911221571, 1765.37491433789, 1766.52645167058, 1759.16736345991, 1768.0339069201, 1768.41658500383, 1770.43932823018, 1771.96715019445, 1772.22896222032, 1773.11175375391, 1774.86467994555, 1774.41461612804, 1776.04796596354, 1772.33884713417, 1774.17031555669, 1777.44056246415, 1780.01903370787, 1778.52021806719, 1782.37618932061, 1783.96373205174, 1782.71231019068, 1785.82025090541, 1786.8879475519, 1787.26217997289, 1788.44119200891, 1788.49111348491, 1785.24253602826, 1791.22490168853, 1791.17839549097, 1793.96614341913, 1791.49073116144, 1795.27153064307, 1796.17734001707, 1796.82804362052, 1798.44668610134, 1798.5443405764, 1798.79010847848, 1801.73720440609, 1802.86573119296, 1803.26865910815, 1804.9126179903, 1805.64655178685, 1802.96649494997, 1802.15403498733, 1801.90925325399, 1805.15230097709, 1810.00844850812, 1804.15206691445, 1809.31279669602, 1813.02486719912, 1813.1668207382, 1815.80757872417, 1808.05843943346, 1817.1718337063, 395033.691886822, 1818.33833680201, 1818.90400230577, 1821.47332137875, 1822.88658038019, 1821.85659511977, 1824.92105489435, 1819.73166990084, 1826.45983383473, 1827.05351784603, 1828.46998117221, 1829.89919608068, 1830.76033490754, 1831.21838127423, 1831.41429819695, 1833.15725758639, 1834.11748520721, 1832.02879060923, 1833.03298368957, 1837.08470700479, 1833.31864024715, 1839.39309670077, 1840.56656094913, 1840.66874834563, 1839.38665305766, 1843.46222911223, 1844.85660605298, 1843.44058657146, 1846.21245173421, 1846.58695062166, 1839.43044575064, 1849.54576739322, 1850.24163392504, 1851.55952150991, 1852.30779376038, 1853.6462255387, 1852.02030059111, 1855.74851539598, 1856.38016698658, 1851.51455949517, 1850.87475401508, 1851.828458044, 1860.62500015246, 1861.97219525661, 1857.30814494912, 1863.57472095591, 1859.6469191253, 1865.08601159557, 1866.10634012447, 1866.93014081207, 1868.72275105832, 1867.47860246717, 1870.72795596961, 1868.18061063809, 1872.42682301801, 1873.39213806051, 1873.49405496001, 1875.8112670746, 1875.25758570193, 1873.33716414663, 1878.09584110365, 1878.45283378851, 1875.79403090976, 1878.01829029343, 1882.5571285827, 1883.24995908285, 1882.71075282231, 1885.08661427895, 1885.20890717167, 1887.4567578621, 1888.29551124523, 1889.95339660186, 1890.3359577947, 1889.19569195133, 1892.56903174038, 1892.33193938529, 1885.39308589554, 1895.62867838645, 1890.67938012179, 1897.43897595786, 1898.807578798, 1899.37343781546, 1897.19168334724, 1901.77148710242, 1901.42953241539, 1900.82978341708, 1904.45829220034, 1904.96561247139, 1905.28956200094, 1907.79478950252, 1907.78918838202, 1909.50344550966, 1910.87204717064, 1910.86970942322, 1912.93887800119, 1907.77965054997, 1913.20252610288, 1915.73331374364, 1916.9567127134, 1917.2602681165, 1918.17065895385, 1916.71973369804, 1920.25615206983, 1913.87791306735, 1922.43041757087, 1923.30727827153, 1924.55259464292, 1924.5820699301, 1924.33378445584, 1927.95740553376, 1928.56747824575, 1925.47522902318, 1930.94454